### PR TITLE
Use docker-compose

### PR DESCRIPTION
**Pull request by chaspy**
close: #2 

ref: https://docs.docker.com/compose/overview/
If you wouldn't have docker-compose, please download it from https://docs.docker.com/compose/install/
Just download and place it where the path passes.

I removed most of build_and_run.sh. The following is unnecessary.
- check if container is running
- check if volume directory exists

@ariririri 
Please review and merge.

### CODE REVIEW

**Comment by chaspy** [comment]
Note: If you just run `/bin/bash`, you can following.

```
$ docker-compose build
$ docker-compose run ask /bin/bash
```

**Comment by ariririri** [comment]
`docker-compose.yml` looks  two container_name. That is correct?

**Comment by chaspy** [comment]
@ariririri 
Indeed. addressed. https://github.com/chaspy/ask/pull/5/commits/034f52b0ba2be0f203a40c25148b0a3a106f73d4

**Comment by ariririri** [comment]
looks Good to me.Thanks

**Pull request merged**
